name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-go:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Download dependencies
        run: |
          cd go && go mod download

      - name: Run go vet
        run: |
          cd go && go vet ./...

      - name: Run tests
        run: |
          cd go && go test -v -race -coverprofile=coverage.out ./...
